services:
  - type: web
    name: trackfit-ai-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python exercise_tracker_api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8080 