services:
  - type: web
    name: trackfit-ai-api
    env: python
    buildCommand: pip install -r requirements_render.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PORT
        value: 5000 